name: Django CI

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: flake8 .

  test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          touch .env
          echo '"${{ secrets.ENV_FILE }}"' | sed "s/\"//g" > .env

      - name: Run test
        run: python manage.py test

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          touch .env
          echo '"${{ secrets.ENV_FILE }}"' | sed "s/\"//g" > .env

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2

      - name: Start containers with Docker Compose
        run: docker-compose up -d



#  deploy:
#      needs: build
#      runs-on: ubuntu-latest
#
#      steps:
#        - name: Set up SSH
#          uses: webfactory/ssh-agent@v0.9.0
#          with:
#            ssh-private-key: ${{ secrets.SSH_KEY }}
#
#        - name: Deploy to server
#          run: |
#            ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
#            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:${{ github.sha }}
#            sudo docker stop myapp || true
#            sudo docker rm myapp || true
#            sudo docker run -d --name myapp -p 80:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:${{ github.sha }}
#            EOF



#      - name: Build images with Docker Compose
#        run: docker compose -f docker-compose.yml build
#
#      - name: Push all images to Docker Hub
#        run: docker compose -f docker-compose.yml push

#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Check out code
#        uses: actions/checkout@v3
#
#      - name: Set up SSH
#        uses: webfactory/ssh-agent@v0.9.0
#        with:
#          ssh-private-key: ${{ secrets.SSH_KEY }}
#
#      - name: Copy docker-compose.yml to server
#        run: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:~
#
#      - name: Deploy to server
#        run: |
#          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
#          sudo docker compose pull
#
#          sudo docker compose down
#          sudo docker compose up -d
#
#          EOF
